---
- name: Install apps
  hosts: localhost
  connection: local
  ignore_errors: "{{ ALLOW_ERRORS }}"
  vars:
    homebrew_apps_to_install: [ "vim", "obsidian", "tree", "tmux", "curl", "sops", "vercel-cli", "terraform-docs"]

  tasks:
    - name: Install homebrew
      ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install homebrew apps
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
      loop: "{{ homebrew_apps_to_install }}"

    - name: Create symlink for tmux config
      file:
        src: "{{ playbook_dir }}/configs/.tmux.conf"
        dest: ~/.tmux.conf
        state: link
